project_id = "fydpeoqwdnjfxxdsxvws"

[functions.create-staff]
verify_jwt = false

[functions.send-patient-invite]
verify_jwt = false

[functions.extract-form-template]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.password-reset]
verify_jwt = false

[functions.send-doctor-invite]
verify_jwt = false

[functions.submit-public-form]
verify_jwt = false

[functions.list-staff]
verify_jwt = false

[functions.update-staff]
verify_jwt = false

[functions.reset-staff-password]
verify_jwt = false

[functions.set-staff-status]
verify_jwt = false

[functions.delete-staff]
verify_jwt = false
